### ISSUE TITLE
Plot markers: labels and symbols are clipped

### ISSUE THREAD

**Issue by luc-j-bourhis** [PlotPyStack/PythonQwt#82]
Consider the code
```
from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.QtCore import Qt
import qwt
import numpy as np

app = QtWidgets.QApplication([])
x = np.linspace(0, 4*np.pi, 100)
y = np.cos(x)
plot = qwt.QwtPlot("Sine function")
plot.enableAxis(plot.xBottom, False) #|Disable axes enabled by default
plot.enableAxis(plot.yLeft, False)   #|
plot.insertLegend(qwt.QwtLegend(), qwt.QwtPlot.BottomLegend)
qwt.QwtPlotCurve.make(x, y, "Sinus", plot, linecolor="blue", antialiased=True)
c = QtGui.QColor('purple')
sz = 10
s = qwt.QwtSymbol.make(
    style=qwt.QwtSymbol.Ellipse,
    brush=QtGui.QBrush(c), pen=QtGui.QPen(c),
    size=QtCore.QSize(sz, sz))
step = 5
for xi, yi in zip(x[::step], y[::step]):
    l = qwt.QwtText.make(text=f'{yi:0.2f}', pointsize=8)
    qwt.QwtPlotMarker.make(
        xvalue=xi, yvalue=yi,
        label=l,
        symbol=s,
        align=Qt.AlignTop,
        plot=plot)
plot.resize(1200, 600)
plot.show()
app.exec_()
```
and the attached outcomes: the green arrows drawn by hand shows where the circles used as markers and their associated text labels are clipped by the plot boundary. So it seems PythonQwt only make the curve fits but not the rest. I would consider that a bug but then is there a way to work around it?
![clipped](https://github.com/PlotPyStack/PythonQwt/assets/295281/9e6fba33-5a8c-415d-b9f7-79b90c344543)

**Comment by PierreRaybaut** [comment]
Thanks for the feedback.
Somehow I was waiting for this issue for quite some time, in a sense. The absence of margins in plots have been a recurring problem lately, for some applications.

I'll be back to you shortly.

For example, this is better I guess:

![image](https://github.com/PlotPyStack/PythonQwt/assets/1311787/40fe72b9-03e0-48c3-8c7a-38fee28e335e)

**Comment by luc-j-bourhis** [comment]
That plot would make me very happy!

**Comment by luc-j-bourhis** [comment]
I am testing it in my software: so far so good. Even with using setAxisScale with the minimum and maximum ordinate does not result in the labels or the markers being clipped. Thanks!

**Comment by PierreRaybaut** [comment]
You're very welcome.

By the way, if you're looking for more high-level features for visualizing curves and images, you may take a look at [PlotPy](https://github.com/PlotPyStack/plotpy) which is based on PythonQwt.

**Comment by luc-j-bourhis** [comment]
Thanks for the pointer: from a quick look at the documentation, it looks like PlotPy supports panning and dragging out of the box. Does it? Does PythonQwt support those features too? The use case I have in mind in the user clicking on the graph, and dragging to pan a graph that is larger than the window displaying it.

**Comment by PierreRaybaut** [comment]
Exactly, zoom/pan features are not implemented in PythonQwt but are available in PlotPy.

**Comment by luc-j-bourhis** [comment]
I will seriously look into PlotPy then! Thanks again!
