### ISSUE TITLE
Different logarithmic scale behavior when compared to Qwt

### ISSUE THREAD

**Issue by nicoddemus** [PlotPyStack/PythonQwt#94]
Hi folks,

We are having different results when using the logarithmic scale compared with `Qwt`.

# Qwt

```python
from PyQt5.QtWidgets import QApplication
from Qwt5 import QwtPlot, QwtPlotCurve, QwtLog10ScaleEngine


app = QApplication([])
plot = QwtPlot()
plot.setWindowTitle("Qwt")
plot.resize(800, 600)

y = [1, 500, 1000, 1500]
x = [1, 2, 3, 4]

curve = QwtPlotCurve()
curve.setData(x, y)

engine = QwtLog10ScaleEngine()
plot.setAxisScaleEngine(QwtPlot.yLeft, engine)

curve.attach(plot)
plot.show()
app.exec()
```

![image](https://github.com/user-attachments/assets/8c443ef1-665a-4417-bf99-5c7715799ea7)

# PythonQwt

```python
from PyQt5.QtWidgets import QApplication
from qwt import QwtPlot, QwtPlotCurve, QwtLogScaleEngine


app = QApplication([])
plot = QwtPlot()
plot.setWindowTitle("PythonQwt")
plot.resize(800, 600)

y = [1, 500, 1000, 1500]
x = [1, 2, 3, 4]

curve = QwtPlotCurve()
curve.setData(x, y)

engine = QwtLogScaleEngine()
plot.setAxisScaleEngine(QwtPlot.yLeft, engine)

curve.attach(plot)
plot.show()
app.exec()
```

![image](https://github.com/user-attachments/assets/b8621033-7c7b-41fa-9f0a-b7572a7c2b03)

---

The original `Qwt` scale looks right, but `PythonQwt` is not really logarithmic... any ideas what the problem might be? I suspect it might be related to the fact that now `PythonQwt` uses a better overall auto range calculation to give some room on each side of each axis (which looks much better in normal situations), but this extra room might not be playing well with the old logarithmic scaling code, but this is just a hunch.

I did look at the [`QwtLogScaleEngine.autoScale` method](https://github.com/PlotPyStack/PythonQwt/blob/582289a8f29972690e1567a2d423e4894f42bcaf/qwt/scale_engine.py#L643-L714) in comparison [with the original](https://sourceforge.net/p/qwt/code/HEAD/tree/trunk/qwt/src/qwt_scale_engine.cpp#l798), and everything seems well.

Any hints/suggestions would be greatly appreciated! 👍

**Comment by PierreRaybaut** [comment]
After a quick overview, still no clue.
I'll have to look further into it.

**Comment by PierreRaybaut** [comment]
After some debugging, I confirm that everything works as expected in `autoScale` method (and in all functions and methods called in it).

I found out that this is coming from commit 3cf995f.

**Comment by PierreRaybaut** [comment]
@nicoddemus : please confirm that it's fixed on your side. Should be 🤞

**Comment by nicoddemus** [comment]
Yep, I can confirm it works great, thanks a lot for this!

**Comment by nicoddemus** [comment]
A new release soon would be great, thanks! But no rush though.
